apiVersion: v1
kind: Service
metadata:
  name: guestbook-service
  labels:
#    name: guestbook-deployment-service
    app: demo-guestbook-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
#     name: guestbook-pod
     app: demo-guestbook-app
     apptype: frontend



